<?php 
$helper      = $this->helper('Lof\SocialLogin\Helper\Data');
$style_popup = $helper->getConfigValue('sociallogin/general/popup_layout'); 
$header_link = $helper->getConfigValue('sociallogin/general/header_link'); 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if(!$customerSession->isLoggedIn()):
   if ($block->isEnabled()): 
    ?>
    <div id="social-login-popup" class="white-popup mfp-with-anim mfp-hide lof-social-login-color lof-social-login <?= $style_popup;?>">
        <?= $block->getChildHtml('popup.authentication');?>
        <?= $block->getChildHtml('popup.forgot') ?> 
        <?= $block->getChildHtml('popup.create') ?>  
    </div>
    <div style="clear: both"></div>
    <script>
        require(['lof/sociallogin/form'], function (SocialLoginForm) {
            var config = {
                socialLoginPopup: '#social-login-popup',
                popupEffect: '<?= $block->getPopupEffect()?>',
                header: '<?= $header_link; ?>',
                section: '',
                ajaxLoad: '#social-login-popup .ajax-loading', 
                authentication: '.social-login.authentication',
                authenticationContent: '.social-login.authentication',
                socialFormLogin: '#social-form-login',
                btnAuthentication: '#bnt-social-login-authentication',
                btnRemind: '#social-form-login .action.remind',
                btnCreate: '#social-form-login .action.create',
                formLoginUrl: '<?= $block->getFormLoginUrl();?>', 
                socialLoginForgot: '.social-login.forgot',
                socialLoginForgotContent: '.social-login.forgot',
                socialFormPassword: '#social-form-password-forget',
                btnSendForget: '#social-form-password-forget .action.send',
                btnbackForget: '#social-form-password-forget .action.back',
                forgotFormUrl: '<?= $block->getForgotFormUrl();?>',
                socialLoginCreate: '.social-login.create',
                socialLoginCreateContent: '.social-login.create',
                socialFormCreate: '#social-form-create',
                btnSocialFormCreate: '#social-form-create .action.create',
                btnSocialFormCreateBack: '#social-form-create .action.back',
                socialFormCreateUrl: '<?= $block->getCreateFormUrl();?>',  
            };
            new SocialLoginForm(config);
        })
        require(['jquery', 'lof/sociallogin/popup'], function ($) {
            $('<?= $header_link; ?>').magnificPopup({
                delegate: 'a.social-login',
                removalDelay: 500, //delay removal by X to allow out-animation
                callbacks: {
                    beforeOpen: function () {
                        this.st.mainClass = this.st.el.attr('data-effect');
                    }
                },
                midClick: true // allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source.
            });

            $('.section-item-content').magnificPopup({
                delegate: 'a.social-login',
                removalDelay: 500, //delay removal by X to allow out-animation
                callbacks: {
                    beforeOpen: function () {
                        this.st.mainClass = this.st.el.attr('data-effect');
                    }
                },
                midClick: true // allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source.
            });
        });

    </script>
<?php endif;
endif; ?>