<div class="social-login block-container forgot" style="display:none">
    <div class="social-login-title">
        <h2 class="forgot-pass-title">
            <?= __('Forgot Password') ?>
        </h2>
    </div>
    <div class="block col-mg mg-12"> 
        <div class="block-content">
            <form class="form-password-forget"
            id="social-form-password-forget"
            data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */
            echo __('* Required Fields') ?>">
            <div class="field note"><?php /* @escapeNotVerified */
                echo __('Please enter your email address below to receive a password reset link.'); ?></div>
                <div class="field email required">
                    <label for="email_address" class="label"><span><?php /* @escapeNotVerified */
                        echo __('Email') ?></span></label>

                        <div class="control">
                            <input type="email" name="email" alt="email" id="email_address" class="input-text"
                            value="<?= $block->escapeHtml($block->getEmailValue()) ?>"
                            data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info'); ?>
                    <?= $block->getChildHtml('forgot.captcha'); ?>

                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="button" class="action send primary"><span><?php /* @escapeNotVerified */
                            echo __('Reset My Password') ?></span></button>
                        </div>
                        <div class="secondary">
                            <a class="action back" href="#"><span><?php /* @escapeNotVerified */
                                echo __('Go back') ?></span></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
