<?php
$helper        = $this->helper("Lof\SocialLogin\Helper\Data");
$social_enable = json_decode($helper->getSocialPosition());
$list_social   = [];
foreach ($social_enable as $key => $v) {
	array_push($list_social, $v->id);
}
?>
<div class="lof-social-login-widget lof-social-customer lof-social-login lof-social-login-color">
	<h3>
		<span><?php echo  __("OR") ?></span>
	</h3>
	<div class="social-login-authentication-channel row">
		<?php foreach($list_social as $key => $v){ ?>
		<?php
		$title        = $helper->getConfigValue('sociallogin/' . $v . '/title_social');
		$id           = 'btn_' . $v . '_login_widget' . time();
		$popup_width  = $helper->getConfigValue('sociallogin/' . $v . '/popup_width'); 
		$popup_height = $helper->getConfigValue('sociallogin/' . $v . '/popup_height'); 
		?>
		<div class="actions-toolbar social-btn <?php echo $v ?>-login col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<div class="primary">
				<button class="action" type="button" id="<?php echo $id; ?>" data-social="<?php echo $v ?>">
					<span>
						<span><i class="fa fa-<?php echo $v ?> icon-social" aria-hidden="true"></i></i><?php echo $title ?></span>
					</span>
				</button>
			</div>
			<script type="text/javascript">
				require(['jquery', 'lof/sociallogin'], function ($, SocialLoginPopup) {
					jQuery(document).ready(function($) {
						$(document).on('click', '#<?php echo $id; ?>', function(e) {
							e.preventDefault();
							var twPopup = new SocialLoginPopup(<?php echo $popup_width ?>, <?php echo $popup_height; ?>);
							twPopup.openPopup('<?php echo $block->getLoginUrl($v); ?>', '<?php echo __('Login')?>');
						});
					});
				});
			</script>
		</div>
		<?php } ?>
	</div>
</div>