<?php  
$style_color = $block->getStyleColor();
$help          = $this->helper("Lof\SocialLogin\Helper\Data");
$facebook      = $help->getStyleColorFacebook();
$google        = $help->getStyleColorGoogle();
$twitter       = $help->getStyleColorTwitter();
$linkedin      = $help->getStyleColorLinkedin();
$github        = $help->getStyleColorGithub();
$instagram     = $help->getStyleColorInstagram();
$wordpress     = $help->getStyleColorWordpress();
$stackoverflow = $help->getStyleColorStackoverflow();
$paypal        = $help->getStyleColorPaypal();
$disqus        = $help->getStyleColorDisqus();
$amazon        = $help->getStyleColorAmazon();
$vimeo         = $help->getStyleColorVimeo();
$pinterest     = $help->getStyleColorPinterest();
$dropbox       = $help->getStyleColorDropbox();
$soundcloud    = $help->getStyleColorSoundcloud();
$windowslive   = $help->getStyleColorWindowslive();
$foursquare    = $help->getStyleColorFoursquare();
$twitch        = $help->getStyleColorTwitch();
$slack        = $help->getStyleColorSlack();
$weibo        = $help->getStyleColorWeibo();
$wechat        = $help->getStyleColorWechat();

?>
<style>
#social-login-popup .social-login-title {
    background-color: <?= $style_color?>
}
#social-login-popup .social-login #bnt-social-login-authentication {
    background-color: <?= $style_color?>;
    border:<?= $style_color?>
}
#social-login-popup .forgot .primary button {
    background-color: <?= $style_color?>;
    border:<?= $style_color?>
}
#social-login-popup .create .primary button {
    background-color: <?= $style_color?>;
    border:<?= $style_color?>
} 
.lof-social-login-color .facebook-login button {
    background : <?= $facebook?>;  
} 
.lof-social-login-color .google-login button {
    background : <?= $google?>;  
} 
.lof-social-login-color .twitter-login button {
    background : <?= $twitter?>;  
} 
.lof-social-login-color .linkedin-login button {
    background : <?= $linkedin?>;  
}
.lof-social-login-color .github-login button {
    background : <?= $github?>;  
}
.lof-social-login-color .instagram-login button {
    background : <?= $instagram?>;  
} 
.lof-social-login-color .wordpress-login button {
    background : <?= $wordpress?>;  
}
.lof-social-login-color .stackoverflow-login button {
    background : <?= $stackoverflow?>;  
}
.lof-social-login-color .paypal-login button {
    background : <?= $paypal?>;  
}
.lof-social-login-color .disqus-login button {
    background : <?= $disqus?>;  
}
.lof-social-login-color .amazon-login button {
    background : <?= $amazon?>;  
}
.lof-social-login-color .pinterest-login button {
    background : <?= $pinterest?>;  
}
.lof-social-login-color .vimeo-login button {
    background : <?= $vimeo?>;  
}
.lof-social-login-color .dropbox-login button {
    background : <?= $dropbox?>;  
} 
.lof-social-login-color .soundcloud-login button {
    background : <?= $soundcloud?>;  
}
.lof-social-login-color .windowslive-login button {
    background : <?= $windowslive?>;
}
.lof-social-login-color .foursquare-login button {
    background : <?= $foursquare?>;
}
.lof-social-login-color .twitch-login button {
    background : <?= $twitch?>;
}
.lof-social-login-color .slack-login button {
    background : <?= $slack?>;
} 
.lof-social-login-color .weibo-login button {
    background : <?= $weibo?>;
}  
.lof-social-login-color .wechat-login button {
    background : <?= $wechat?>;
}
<?= $block->getCustomCss() ?>
</style>
